export const activeSpots = [
'Steamer Lane',
'Oceanside Harbor',
'Oceanside Pier',
'Tamarack',
'Terra Mar',
'Ponto',
'Grandview',
'Beacons',
'Moonlight Beach',
'D Street',
'Swamis',
'Pipes',
'Cardiff Reef',
'Georges',
'Seaside Reef',
'Del Mar Rivermouth',
'15th Street - Del Mar',
'Torrey Pines State Beach',
'Blacks Beach',
'Scripps Pier',
'Horseshoe',
'Windansea',
'Bird Rock',
'Tourmaline',
'Pacific Beach',
'Mission Beach',
'Ocean Beach Jetty',
'Ocean Beach Pier',
'Sunset Cliffs',
'Imperial Beach',
'Seal Beach Pier',
'Surfside Jetty',
'Anderson St',
'Bolsa Chica',
'Swell: Poor-Fair',
'Goldenwest',
'17th Street',
'Huntington Pier',
'Huntington Beach',
'Santa Ana River Jetties',
'56th Street',
'40th Street',
'36th Street',
'Blackies',
'Newport Pier',
'The Wedge',
'Salt Creek',
'Doheny',
'San Clemente Pier',
'T Street',
'Lasuen',
'Riviera',
'Calafia',
'State Beach',
'Cottons Point',
'Upper Trestles',
'Lower Trestles',
'Church',
'San Onofre',
'Trails',
'County Line',
'Leo Carrillo',
'Zuma Beach',
'Point Dume',
'Malibu',
'Topanga',
'Chart House',
'Sunset',
'Santa Monica Municipal Pier',
'Venice',
'El Porto',
'Manhattan Beach',
'Hermosa',
'Redondo Breakwater',
'Topaz Street',
'Torrance Beach',
'Palos Verdes Cove',
'La Conchita',
'Hobsons',
'Faria',
'Mondos',
'Emma Wood',
'C Street',
'Jalama',
'Refugio',
'Sands',
'Devereux',
'Campus Point',
'Leadbetter',
'Rincon',
'Morro Rock',
'Pismo Beach Pier',
'Moss Landing State Beach',
'Carmel Beach',
'Sand Dollar',
'County Line',
'Waddell Creek',
'Waddell Reefs',
'Scotts Creek',
'Davenport Landing',
'Four Mile',
'Three Mile',
'Natural Bridges',
'Stockton Avenue',
'Getchell',
'Mitchells Cove',
'Cowells',
'The Rivermouth',
'Blacks',
'Santa Marias',
'26th Avenue',
'Little Windansea',
'Rockview',
'Sewer Peak',
'Pleasure Point',
'38th Avenue',
'The Hook',
'Sharks Cove',
'Capitola Jetties',
'Manresa',
'Montara',
'Mavericks',
'Princeton Jetty',
'Pomponio State Beach',
'Ano Nuevo',
'Eagles Point',
'Ocean Beach - Kellys Cove',
'Ocean Beach - VFW',
'Ocean Beach - Noriega',
'Bolinas',
'Fort Cronkhite',
]
